### PR TITLE
Adding Boot Policy

### PR DESCRIPTION
**Pull request by ratagupt**
Adding the boot policy support for get/Set system boot option.Policy can be onetime which is applicable to next boot only or 
Permanent which is applicable for all the future boots.

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/phosphor-host-ipmid/83)

### CODE REVIEW

**Comment by ratagupt** [comment]
Added the review comments for 146621

**Comment by vishwabmc** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[chassishandler.C, line 131 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/83#-KFiEHCabi0V8hGGraJd:-KFiEHCabi0V8hGGraJe:1087491977) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/2fcb29491020c8acbb949acebd4f1b12f516e9d3/chassishandler.C#L131)):*
extra tab here... remove it.

put this in vimrc   match Todo /\s\+$/

---

*[chassishandler.C, line 158 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/83#-KFiJC2rjLWECQ0X0bX9:-KFiJC2s9dJI1xUA2bhH:1085880116) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/2fcb29491020c8acbb949acebd4f1b12f516e9d3/chassishandler.C#L158)):*
m = sd_bus_message_unref(m)

---

*[chassishandler.C, line 199 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/83#-KFiFAAqKfjRyiWJj1xn:-KFiEfCOrdIjneHvf6ZQ:-1132062688) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/2fcb29491020c8acbb949acebd4f1b12f516e9d3/chassishandler.C#L199)):*
extra tab

---

*[chassishandler.C, line 376 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/83#-KFi5wsvKYHJv0meBQ8O:-KFi5wsvKYHJv0meBQ8P:184668873) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/2fcb29491020c8acbb949acebd4f1b12f516e9d3/chassishandler.C#L376)):*
Think these need to be at the top of file post #defines.

---

*[chassishandler.C, line 379 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/83#-KFiFgWzfvTM0hffdR9O:-KFiFgWzfvTM0hffdR9P:-2051087227) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/2fcb29491020c8acbb949acebd4f1b12f516e9d3/chassishandler.C#L379)):*
does it make sense to move 0x40 below 0xC0

---

*[chassishandler.C, line 495 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/83#-KFiLPZWk6wCJetjyFvV:-KFiLPZXZV2q4vmzRQOA:-1588323311) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/2fcb29491020c8acbb949acebd4f1b12f516e9d3/chassishandler.C#L495)):*
should 's' not be const char * ?

also is it not other way ?. Looks like we are saying " If I see ONETIME, then I set it as perPERMANENT, else I set it as "ONETIME".

I agree it works but its a bit crypt... Does it make sense to make it to easily understandable if and else ?

---

*[chassishandler.C, line 504 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/83#-KFiGTCbo1DMXJoaMOFX:-KFiGTCcylNB5rtUSVYI:1489353657) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/2fcb29491020c8acbb949acebd4f1b12f516e9d3/chassishandler.C#L504)):*
move } below if

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/83)*

**Comment by ratagupt** [comment]
Hi Vishwa,
 
Thanks for the review.
 
Few clarifications are inline.
 
Regards
Ratan
 
 
----- Original message -----From: vishwabmc <notifications@github.com>To: openbmc/phosphor-host-ipmid <phosphor-host-ipmid@noreply.github.com>Cc: Ratan K Gupta/India/IBM@IBMINSubject: Re: [openbmc/phosphor-host-ipmid] Adding Boot Policy (#83)Date: Tue, Apr 19, 2016 5:22 PM 
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.
chassishandler.C, line 131 [r2] (raw file):extra tab here... remove it
put this in vimrc match Todo /\s+$/
   RG>>>Done,But I am not sure "match Todo"...How can it help in removing Extra Tab .Seems to me it is typo mistake.
       >>>>It can Highlight the Todo in the code.
chassishandler.C, line 158 [r2] (raw file):m = sd_bus_message_unref(m)
It makes sense if It(m) is being used later in the code,But it is EOF so seems we can ignore it.
chassishandler.C, line 199 [r2] (raw file):extra tab
chassishandler.C, line 376 [r2] (raw file):Think these need to be at the top of file post #defines.
chassishandler.C, line 379 [r2] (raw file):does it make sense to move 0x40 below 0xC0
chassishandler.C, line 495 [r2] (raw file):should 's' not be const char * ?
   RG>>>> I thought to make it const char but s is being used in the above code where it is being used as char *.
also is it not other way ?. Looks like we are saying " If I see ONETIME, then I set it as perPERMANENT, else I set it as "ONETIME".
I agree it works but its a bit crypt... Does it make sense to make it to easily understandable if and else ?
    RG>>> I change the name of the MACRO to make it more readable.
chassishandler.C, line 504 [r2] (raw file):move } below if
Comments from Reviewable

**Comment by anoo1** [comment]
@vishwabmc Could you review Ratan's updated changes?

**Comment by vishwabmc** [comment]
@anoo1: Ratan and I had walked through this couple weeks before and I found it okay. There have been no further changes since we last reviewed.

**Comment by anoo1** [comment]
@ratagupt Could you refresh the settings PR? It has branch conflicts and it's a co-req with this change.
https://github.com/openbmc/phosphor-settingsd/pull/8

**Pull request merged**
