### PR TITLE
Support for restricted mode for IPMI commands

### PR DESCRIPTION
**Pull request by tomjoseph83**
Only IPMI whitelisted commands are supported in restricted mode.Following commands are restricted in restricted mode.

Blacklisted Commands:
==================

1) Warm Reset  (Netfn: APP, Cmd: 0x02)
2) Set LAN Parameters  (Netfn: STORAGE, Cmd: 0x01)
4)Set ACPI Power State - Currently No Op
5) Wilcard Commands(APP, CHASSIS, SENSOR, STORAGE, TRANSPORT) - Currently No Op

Whitelisted Commands:
==================
===================

[App] Get BT Capabilities (0x36)
[App] Reset Watchdog (0x22)
[App] Set watchdog (0x24)
[App] Get Device GUID
[App] Read Event Message Buffer
[App] Set BMC Global Enables
[App] Get Message Flags
[App] Get Channel Info

[Chassis] Get System Boot Options
[Chassis] Chassis Control
[Chassis] Set System Boot Options

[DCMI] Get Power Limit
[GRP] Group Extn Command

[Sensor/Event] Get Sensor Type (0x2F)
[Sensor/Event] Set Sensor Reading
[Sensor/Event] Get Sensor Reading

[Storage] Get SEL time
[Storage] Set SEL time
[Storage] Get SEL info (0x40)
[Storage] Reserve SEL
[Storage] Add SEL Entry

[Transport] Get LAN parameters

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/phosphor-host-ipmid/81)

### CODE REVIEW

**Comment by mdmillerii** [comment]
Since we only have 1 permission (restricted or unrestricted) I won't complain about the code being done in each function.  Otherwise I would advocate some centralized table or registration parameter.

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[apphandler.C, line 10 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KED9a3TF_9-CHexhNfm:-KED9a3TF_9-CHexhNfn:276176493) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b68c66ddb92e6bacf45d346d2b14e8426acc21a0/apphandler.C#L10)):*
All of these extern statements should be in a single header file, and that should be exported to the oem api.

---

*[ipmid.C, line 18 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KEDA-NYsq6pykyUdLkB:-KEDA-NYsq6pykyUdLkC:-1481906324) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b68c66ddb92e6bacf45d346d2b14e8426acc21a0/ipmid.C#L18)):*
I would put this comment in the header file with the extern.

And that does seem to be the style in this project.

---

*[ipmid.C, line 19 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KEDChJNsk6_oFC1xbwN:-KEDChJOYmCP1l4HZu5q:-611812822) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b68c66ddb92e6bacf45d346d2b14e8426acc21a0/ipmid.C#L19)):*
As mentioned below, while the setting should default unrestricted the code should assume restricted until confirmed unrestricted.

---

*[ipmid.C, line 256 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KEDBqDi9Iuh8S3uV9xd:-KEDBqDi9Iuh8S3uV9xe:-1822278890) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b68c66ddb92e6bacf45d346d2b14e8426acc21a0/ipmid.C#L256)):*
I advocate: If we have trouble retrieving the state we should fail "safe" and say restricted.

Thoughts?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-:-KEDDGAIICbnlXmOhDgv:665762392)*

**Comment by tomjoseph83** [comment]
Agree with you on this. My initial plan was to have it as registration parameter. Since it was only one permission and blacklisted functions are very less, I  went ahead with the current plan

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[apphandler.C, line 10 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KED9a3TF_9-CHexhNfm:-KEjja7R04n3i8gwd0fB:676635175) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b68c66ddb92e6bacf45d346d2b14e8426acc21a0/apphandler.C#L10)):*
Done

---

*[ipmid.C, line 18 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KEDA-NYsq6pykyUdLkB:-KEjje82JSxuqWIMk9-0:-1935649954) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b68c66ddb92e6bacf45d346d2b14e8426acc21a0/ipmid.C#L18)):*
We will use uint8_t instead of bool. Because ipmid-api.H is include in hostservices.c( C File)

---

*[ipmid.C, line 19 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KEDChJNsk6_oFC1xbwN:-KEjjhCmXYj4-kMzqurv:1335659019) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b68c66ddb92e6bacf45d346d2b14e8426acc21a0/ipmid.C#L19)):*
The box would be initially in unrestricted mode. Once the Lan parameters are set...(example).. then the box is moved to restricted mode. The default value of the restricted mode is also false(in settings.py).
I think either value is fine for the restricted mode as we would read the value at the time of startup.

---

*[ipmid.C, line 256 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KEDBqDi9Iuh8S3uV9xd:-KEjkjFy3IBO9LWDtnUv:-658235962) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b68c66ddb92e6bacf45d346d2b14e8426acc21a0/ipmid.C#L256)):*
I  can default and say restricted. My viewpoint was to keep status-quo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-:-KEj__d7OX5AOW57t5a_:-1918895942)*

**Comment by williamspatrick** [comment]
Waiting on updated patch set.

**Comment by williamspatrick** [comment]
Also, please verify comments from Jeremy Kerr on mailing list are addressed.

https://lists.ozlabs.org/pipermail/openbmc/2016-April/002731.html

**Comment by tomjoseph83** [comment]
I am working on the next patch set, would be out tomorrow. I will take into account Jeremy's comments as well.

**Comment by causten** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KI3wTRpoVhnjRO0g1c2:-KI3wTRpoVhnjRO0g1c3:804610288) (no related file):*
This does not adhere to the request from Jeremy, https://lists.ozlabs.org/pipermail/openbmc/2016-April/002731.html
you are allowing the whitelist to be determined at runtime by the .so's themselves.  Remember we wanted a single point for audit.

Your pull request should be only 1 or 2 files.  Create the ipmi_command_is_allowed function and call it before ipmi_netfn_router (in ipmicmd.C)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81)*

**Comment by vishwabmc** [comment]
Review status: 0 of 10 files reviewed at latest revision, 13 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KI3wTRpoVhnjRO0g1c2:-KIDOEspaIZsRaJNp8Vo:-1448903324) (no related file):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> This does not adhere to the request from Jeremy, https://lists.ozlabs.org/pipermail/openbmc/2016-April/002731.html
> you are allowing the whitelist to be determined at runtime by the .so's themselves.  Remember we wanted a single point for audit.
> 
> Your pull request should be only 1 or 2 files.  Create the ipmi_command_is_allowed function and call it before ipmi_netfn_router (in ipmicmd.C)
> 
> 
</details>
Just trying to understand this.. By audit, what are we doing ? Is it a audit person that wants to see what are the white and black listed commands at any given point of time ?.  Is there a requirement to make this available from inside BMC than a document that we can update in the github ? or with the product ?.

---

*[groupext.C, line 28 \[r3\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KIDJdpTmU3X4VXuhIDi:-KIDJdpU4ZZTc_SxJL8a:-1133943498) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/ea9056b938cdb91dcc2b40a914ac059c5bd91f25/groupext.C#L28)):*
> ```
> {
>     printf("Registering NetFn:[0x%X], Cmd:[0x%X]\n",NETFUN_GRPEXT, GRPEXT_GET_GROUP_CMD);
>     ipmi_register_callback(NETFUN_GRPEXT, GRPEXT_GET_GROUP_CMD, NULL, ipmi_groupext, IPMI_WHITELISTED_COMMAND);
> ```

It makes sense to have WHITELIST as default..That way we are reducing the number of changes to only explicitly say BLACK LISTED.

---

*[ipmid-api.h, line 106 \[r3\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KIDKoUoAYQnT9Q1LNf-:-KIDKoUoAYQnT9Q1LNf0:-510353335) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/ea9056b938cdb91dcc2b40a914ac059c5bd91f25/ipmid-api.h#L106)):*
> ```objc
> 
> // In restricted mode only whitelisted commands are executed.
> enum ipmi_command_flag
> ```

Probably  ipmi_cmd_allowed_type ?

---

*[ipmid.C, line 39 \[r3\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KIDLZimA5j1-0xbhZN9:-KIDLZinD8EvT1SVcXPt:-617537771) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/ea9056b938cdb91dcc2b40a914ac059c5bd91f25/ipmid.C#L39)):*
> ```
> 
> const char * FILTER = "type='signal',interface='org.openbmc.HostIpmi',member='ReceivedMessage'";
> const char * RESTRICTED_MODE_FILTER = "type='signal',interface='org.freedesktop.DBus.Properties',path='/org/openbmc/settings/host0'";
> ```

Is it not the interface by settings than the free desktop ?. Or is it because settings does not emit any signal on the changes and hence we are defaulting to free desktop's general property change notifier ?

---

*[ipmid.C, line 162 \[r3\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KIDN8w0POYMJoSueRYy:-KIDN8w10sIS1QGaueDd:-1108585233) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/ea9056b938cdb91dcc2b40a914ac059c5bd91f25/ipmid.C#L162)):*
> ```
>     // If restricted mode is true and command is not whitelisted, don't
>     // execute the command
>     if(restricted_mode && std::get<2>(handler_and_context))
> ```

Make #define to RESTRICTED_MODE 2 than hard coding 2

---

*[ipmid.C, line 167 \[r3\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KIDNQZP_60KXR7ykG0k:-KIDNQZP_60KXR7ykG0l:643875178) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/ea9056b938cdb91dcc2b40a914ac059c5bd91f25/ipmid.C#L167)):*
> ```
>         memcpy(response, &rc, IPMI_CC_LEN);
>         *data_len = IPMI_CC_LEN;
>         return rc;
> ```

Can not return from here. Let the RC flow through.

---

*[ipmid.C, line 176 \[r3\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KIDNfBEQVEWZ5xdgNak:-KIDNfBEQVEWZ5xdgNal:1164843772) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/ea9056b938cdb91dcc2b40a914ac059c5bd91f25/ipmid.C#L176)):*
> ```
> 
>     // Response message from the plugin goes into a byte post the base response
>     rc = (std::get<0>(handler_and_context)) (netfn, cmd, request, respo,
> ```

Better to #define the 0 at the top ?. But why is this change needed ?

---

*[ipmid.C, line 260 \[r3\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KIDIffCYjIgShrUwd0c:-KIDIffCYjIgShrUwd0d:1844884243) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/ea9056b938cdb91dcc2b40a914ac059c5bd91f25/ipmid.C#L260)):*
> ```
>     if(rc < 0)
>     {
>         fprintf(stderr, "Failed to issue call method: %s\n", strerror(-rc));
> ```

Make this a context based trace

---

*[ipmid.C, line 486 \[r3\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81#-KIDIL60PMNAG3TTV6l7:-KIDIL61KvqQ2outaPpQ:-1632765359) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/ea9056b938cdb91dcc2b40a914ac059c5bd91f25/ipmid.C#L486)):*
> ```
>     }
> 
>     // Read restricted mode
> ```

This comment needs to tell the usecase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/81)*

**Comment by williamspatrick** [comment]
I believe there is more code coming for this.  Please resubmit commit in Gerrit after migration.

**Pull request closed without merging**
