### PR TITLE
Implement Network Override

### PR DESCRIPTION
**Pull request by ratagupt**
This change is [Reviewable](https://reviewable.io/reviews/openbmc/phosphor-host-ipmid/90)

### CODE REVIEW

**Comment by vishwabmc** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[chassishandler.C, line 12 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe5TzqFrQlZfGB6hY9:-KJe5TzrJmSyPwJt2YGv:1907737439) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L12)):*
> ```
> //Defines
> #define SET_PARM_VERSION 1
> #define SET_PARM_BOOT_FLAGS_PERMANENT 0x40 //boot flags data1 7th bit on
> ```

more readable if we align 0x40 this with 0x80 ?

---

*[chassishandler.C, line 18 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe5HfQJco1Hpyc7sRD:-KJe5HfQJco1Hpyc7sRE:151437242) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L18)):*
> ```
> #define SIZE_HOST_NETWORK_DATA 26
> #define SIZE_BOOT_OPTION SIZE_HOST_NETWORK_DATA
> //#define INET_ADDRSTRLEN 15
> ```

remove this one ?

---

*[chassishandler.C, line 263 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe61EddRd0S8xshASW:-KJe61EddRd0S8xshASX:-2008196726) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L263)):*
> ```
>          isDHCP = "";
>      }
> };
> ```

struct host_network_config_t my_config = {0}; does it work too ?

---

*[chassishandler.C, line 265 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe6XbJfF1VA8rr224O:-KJe6XbJfF1VA8rr224P:1473754703) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L265)):*
> ```
> };
> 
> uint8_t getHostNetworkData(get_sys_boot_options_response_t* respptr)
> ```

get_sys_boot_options_response_t *respptr ?

---

*[chassishandler.C, line 269 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe7-AIAQbOf4JJJoQv:-KJe7-AIAQbOf4JJJoQw:951465074) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L269)):*
> ```
> 
> 
>     printf ("Inside getHostNetworkData");
> ```

Not really needed tho ?

---

*[chassishandler.C, line 270 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe75EideurUYJi5rON:-KJe75EideurUYJi5rOO:-396338727) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L270)):*
> ```
> 
>     printf ("Inside getHostNetworkData");
>     char * prop = NULL;
> ```

char *prop = NULL;

---

*[chassishandler.C, line 309 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJeCIXPVmtZ-EN8cdiL:-KJeCIXPVmtZ-EN8cdiM:1891218140) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L309)):*
> ```
>         value = token.substr(pos1+1,pos);
> 
>         if ( name == "ipaddress" )
> ```

strtok perhaps ?

---

*[chassishandler.C, line 343 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJeCcYsxbvZOOZfCVEc:-KJeCcYtPbFuo-64q1hJ:999941584) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L343)):*
> ```
>     while (digit != NULL)
>     {
>         int resp_byte = strtoul(digit, NULL, 16);
> ```

resp_byte can be outside of the loop .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90)*

**Comment by causten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 23 unresolved discussions.

---

*[chassishandler.C, line 276 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiELOIGFi2qw1JwJ7G:-KJiELOIGFi2qw1JwJ7H:713424762) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L276)):*
> ```
>     //As first 9 bytes are prefilled so in rest of the bytes we are assigning 0
> 
>     memset( data+9 ,0,(SIZE_BOOT_OPTION-9) );
> ```

This line is so weird, it made me stop and think about it for too long

uint8_t initial_bytes[] = {0x80,0x21, 0x70 ,0x62 ,0x21,0x00 ,0x01 ,0x06 ,0x04};
uint8_t data[SIZE_BOOT_OPTION] = {0};

memcpy(data, initial_bytes, sizeof(initial_bytes));

Less math!

---

*[chassishandler.C, line 299 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiH-0DGb4MjlQJjOu-:-KJiH-0DGb4MjlQJjOu0:-567421909) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L299)):*
> ```
>     string conf_str(prop);
>     
>     printf ("Configuration String[%s]\n ",conf_str.c_str());
> ```

remove this 

---

*[chassishandler.C, line 311 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiH_IJ6JmQr-d5HKKs:-KJiH_IK1FdKapzQaFTC:1086057816) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L311)):*
> ```
>         if ( name == "ipaddress" )
>             host_config.ipaddress = value;
>         else if ( name == "prefix")
> ```

I didn't know you could do that.  Typically it is a strcmp()  

---

*[chassishandler.C, line 321 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiHmebe-opz_0I_yJD:-KJiHmecDRAD9fjHcctJ:972282423) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L321)):*
> ```
> 
>         conf_str.erase(0, pos + delimiter.length());
>         printf ("Name=[%s],Value=[%s],position=[%d]\n",name.c_str(),value.c_str(),pos);
> ```

print in the source can clog the journal.  You sure you want to add it?

---

*[chassishandler.C, line 327 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiI7mkP_npbdrcWJSd:-KJiI7mlpOLvburj-QCR:2023139638) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L327)):*
> ```
>     //If there as an error in converting the mac as number we are not throwing 
>     //error we would be sending 0's for the mac.
>     
> ```

spaces not needed, since you will be editing the file anyway

---

*[chassishandler.C, line 334 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiIDG2cV2kSMvFEpTj:-KJiIDG2cV2kSMvFEpTk:2023139638) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L334)):*
> ```
>         fprintf(stderr, "Unexpected MAC format: %s", host_config.macaddress.c_str());
>     }
>     
> ```

spaces not needed, since you will be editing the file anyway

---

*[chassishandler.C, line 338 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiIELsX5VPez1TrTuV:-KJiIELsX5VPez1TrTuW:2023139638) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L338)):*
> ```
>     //in the strtok_r then digit will be null then we don't need to do 
>     //anything as data is prefilled with 0
>     
> ```

spaces not needed, since you will be editing the file anyway

---

*[chassishandler.C, line 359 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiJD51gKTcWVTAfUUQ:-KJiJD51gKTcWVTAfUUR:1861180524) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L359)):*
> ```
>     index+=4; 
> 
>     printf ("\n===========Printing the Network Conf=====================\n");
> ```

more prints

---

*[chassishandler.C, line 362 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiJZThfxTgJNOJ8NbG:-KJiJZTitDa8iB5U6OYP:1861180524) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L362)):*
> ```
> 
>     for (int j = 0;j<index;j++)
>         printf("%02x ", data[j]);
> ```

more prints

---

*[chassishandler.C, line 371 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiMQvmxqdFim1vdAei:-KJiMQvnFbsQAnKWsNfS:1013668043) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L371)):*
> ```
> uint8_t setHostNetworkData(set_sys_boot_options_t * reqptr)
> {
>     printf ("\n Inside setHostNetworkData***********");
> ```

not a good print, remove this

---

*[chassishandler.C, line 418 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiMU6ZnrWQaCcWTTji:-KJiMU6ZnrWQaCcWTTjj:-627808244) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L418)):*
> ```
> 
> 
>     printf ("Host Config Str= %s\n",host_network_config.c_str());
> ```

This is a good print, you are telling everyone that the network is changing.  Make it more official like "Network configuration changed: %s\n"

---

*[chassishandler.C, line 679 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiLl2uqcmdhlpVmo0c:-KJiLl2uqcmdhlpVmo0d:1179058908) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L679)):*
> ```
> 
> 
>     printf("IPMI SET_SYS_BOOT_OPTIONS reqptr->parameter =[%d]\n",reqptr->parameter);
> ```

you know a few lines up there is another print.  I like yours better because it has more data  

---

*[chassishandler.C, line 716 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiKdQIYKhzldceQ-zb:-KJiKdQIYKhzldceQ-zc:-294492093) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L716)):*
> ```
>        int ret = setHostNetworkData(reqptr);
>        if (ret < 0) {
>            fprintf(stderr, "setHostNetworkData failed for set_sys_boot_options.\n");
> ```

you may want to add the value for ret, that would help debug on an error

---

*[chassishandler.C, line 720 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiKo1yoCfGDkEIZd4a:-KJiKo1yoCfGDkEIZd4b:-1211037758) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L720)):*
> ```
> 
>        }
>     }      
> ```

extra spaces

---

*[chassishandler.C, line 721 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiKqfZ-XOct2-GSu2J:-KJiKqfZ-XOct2-GSu2K:-1211037758) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L721)):*
> ```
>        }
>     }      
>     
> ```

extra spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90)*

**Comment by ratagupt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 23 unresolved discussions.

---

*[chassishandler.C, line 12 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe5TzqFrQlZfGB6hY9:-KJkusokZ2yX68cG00Fv:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L12)):*
<details><summary><i>Previously, vishwabmc wrote…</i></summary>
> more readable if we align 0x40 this with 0x80 ?
</details>
done

---

*[chassishandler.C, line 18 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe5HfQJco1Hpyc7sRD:-KJkuu4LkhmkX-HQm66g:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L18)):*
<details><summary><i>Previously, vishwabmc wrote…</i></summary>
> remove this one ?
</details>
done

---

*[chassishandler.C, line 263 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe61EddRd0S8xshASW:-KJjMFMKodMhMK0n7i7h:333905848) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L263)):*
<details><summary><i>Previously, vishwabmc wrote…</i></summary>
> struct host_network_config_t my_config = {0}; does it work too ?
</details>
Yes it works for a instance,But by creating the constructor if some body doesn't do as above(struct host_network_config_t my_config = {0}) then this constructor will take care, which is the job of constructor to avoid such scenario.

---

*[chassishandler.C, line 265 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe6XbJfF1VA8rr224O:-KJkuwymlBjrnOfwR5jc:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L265)):*
<details><summary><i>Previously, vishwabmc wrote…</i></summary>
> get_sys_boot_options_response_t *respptr ?
</details>
done

---

*[chassishandler.C, line 269 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe7-AIAQbOf4JJJoQv:-KJkuyGS9arGjEP8WLjU:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L269)):*
<details><summary><i>Previously, vishwabmc wrote…</i></summary>
> Not really needed tho ?
</details>
done

---

*[chassishandler.C, line 270 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJe75EideurUYJi5rON:-KJkuz7Q0f1UUEO_It2X:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L270)):*
<details><summary><i>Previously, vishwabmc wrote…</i></summary>
> char *prop = NULL;
</details>
done

---

*[chassishandler.C, line 276 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiELOIGFi2qw1JwJ7G:-KJjZjehsg7caxg7dZtP:-1196727358) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L276)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> This line is so weird, it made me stop and think about it for too long
> 
> uint8_t initial_bytes[] = {0x80,0x21, 0x70 ,0x62 ,0x21,0x00 ,0x01 ,0x06 ,0x04};
> uint8_t data[SIZE_BOOT_OPTION] = {0};
> 
> memcpy(data, initial_bytes, sizeof(initial_bytes));
> 
> Less math!
> 
> 
> 
</details>
Cyril gave a comment that we don't need to assigning the rest of the bytes as it is automatically assigns to 0.
so suppose if we have 20 bytes array and we are initializing the 7 bytes then we don't need to initialize rest 13 bytes as it will automatically initialize to 0.

---

*[chassishandler.C, line 299 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiH-0DGb4MjlQJjOu-:-KJjbjFlxXF-noE543Hx:1185261032) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L299)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> remove this 
</details>
This print is for what we got it from the settings file.So in this function there would be two prints 
1) what we got from the settings file
2) What we returned in IPMI Fromat.

---

*[chassishandler.C, line 311 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiH_IJ6JmQr-d5HKKs:-KJjLxz45TrBOXTz6KB0:1691293030) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L311)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> I didn't know you could do that.  Typically it is a strcmp()  
</details>
It is a std:string overloaded (equal to) operator ,so we can  do it  with c++ string.

---

*[chassishandler.C, line 321 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiHmebe-opz_0I_yJD:-KJjbyXnscqn8OPtS_0O:144596707) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L321)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> print in the source can clog the journal.  You sure you want to add it?
</details>
I am removing this one.

---

*[chassishandler.C, line 327 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiI7mkP_npbdrcWJSd:-KJjc2oUcQmFKsmbxZKE:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L327)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> spaces not needed, since you will be editing the file anyway
</details>
done

---

*[chassishandler.C, line 334 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiIDG2cV2kSMvFEpTj:-KJjc4_1sKaJp8AKhM38:-469593337) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L334)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> spaces not needed, since you will be editing the file anyway
</details>
done.

---

*[chassishandler.C, line 338 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiIELsX5VPez1TrTuV:-KJjc6r4tyiHFbq65oF0:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L338)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> spaces not needed, since you will be editing the file anyway
</details>
done

---

*[chassishandler.C, line 343 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJeCcYsxbvZOOZfCVEc:-KJjc9J6yfNwbYFLaN6R:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L343)):*
<details><summary><i>Previously, vishwabmc wrote…</i></summary>
> resp_byte can be outside of the loop .
</details>
done

---

*[chassishandler.C, line 359 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiJD51gKTcWVTAfUUQ:-KJjKIyrGfLDoniTxfeR:-1813639973) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L359)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> more prints
</details>
This print is for IPMI data..Which is being returned,Conf str is for what we read from the file then we interpret the data and filled it in IPMI format.I think it is needed.
 

---

*[chassishandler.C, line 371 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiMQvmxqdFim1vdAei:-KJjcDPAR5cU1iN9jH3m:-469593373) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L371)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> not a good print, remove this
</details>
done

---

*[chassishandler.C, line 716 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiKdQIYKhzldceQ-zb:-KJkt5JWK85kmglKaBON:-2139678143) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L716)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> you may want to add the value for ret, that would help debug on an error
</details>
I may add but that would be covered in the earlier logs..

---

*[chassishandler.C, line 720 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiKo1yoCfGDkEIZd4a:-KJkuov23VdU0rvmVE8J:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L720)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> extra spaces
</details>
done

---

*[chassishandler.C, line 721 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiKqfZ-XOct2-GSu2J:-KJkuqudTq0jnYl7JMHr:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L721)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> extra spaces
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90)*

**Comment by ratagupt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 23 unresolved discussions.

---

*[chassishandler.C, line 362 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiJZThfxTgJNOJ8NbG:-KJkvQyYgAYJDyJCpB4E:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L362)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> more prints
</details>
done

---

*[chassishandler.C, line 418 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiMU6ZnrWQaCcWTTji:-KJkvWcNachJynSQhp8C:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L418)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> This is a good print, you are telling everyone that the network is changing.  Make it more official like "Network configuration changed: %s\n"
</details>
done

---

*[chassishandler.C, line 679 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiLl2uqcmdhlpVmo0c:-KJkvYjW4zemlSmuUjOT:677588487) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L679)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> you know a few lines up there is another print.  I like yours better because it has more data  
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90)*

**Comment by sammj** [comment]
Review status: 0 of 1 files reviewed at latest revision, 28 unresolved discussions.

---

*[chassishandler.C, line 276 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiELOIGFi2qw1JwJ7G:-KLJPsNGCWTPrMmSTGdw:-2089162521) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L276)):*
<details><summary><i>Previously, ratagupt wrote…</i></summary>
> Cyril gave a comment that we don't need to assigning the rest of the bytes as it is automatically assigns to 0.
> so suppose if we have 20 bytes array and we are initializing the 7 bytes then we don't need to initialize rest 13 bytes as it will automatically initialize to 0.
</details>
Hi Ratan, copying some of my comments from the mailing list;

This "0x80,0x21, 0x70 ,0x62", and indeed the rest of the format are Petitboot-specific. While it's probably fine to assume we're using Petitboot for the moment, at least a comment here would be good to make it obvious for readers that may *not* be running Petitboot on their machines.

---

*[chassishandler.C, line 281 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KLJSiN1vvq_w3EoMP-G:-KLJSiN1vvq_w3EoMP-H:1625657124) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b5133820b90fa73a595885a9ce5ed33bf08f5892/chassishandler.C#L281)):*
> ```
>     /* Parsing the string and fill the hostconfig structure with the 
>      * values */
> ```

Why do we do this? Is there a reason we can't just convert this string into the *other* string and get rid of the hostconfig struct?

---

*[chassishandler.C, line 333 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KLJT5kSwVskTpmCrTVu:-KLJT5kSwVskTpmCrTVv:-1797809955) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b5133820b90fa73a595885a9ce5ed33bf08f5892/chassishandler.C#L333)):*
> ```
> 
>         token = host_config.macaddress.substr(0, pos);
>         resp_byte = strtoul(token.c_str(), NULL, 16);
> ```

You should check strtoul() for errors

---

*[chassishandler.C, line 334 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KLJTBXScramLipgHXzJ:-KLJTBXScramLipgHXzK:516730498) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b5133820b90fa73a595885a9ce5ed33bf08f5892/chassishandler.C#L334)):*
> ```
>         token = host_config.macaddress.substr(0, pos);
>         resp_byte = strtoul(token.c_str(), NULL, 16);
>         memcpy((void*)&respData[index], &resp_byte, 1);
> ```

No need to cast to (void*)

---

*[chassishandler.C, line 351 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KLJU8LS3kKtpdhlb2U9:-KLJU8LS3kKtpdhlb2UA:33734866) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b5133820b90fa73a595885a9ce5ed33bf08f5892/chassishandler.C#L351)):*
> ```
>     sscanf(host_config.prefix.c_str(),"%02d",&respData[index++]);
>     inet_pton(AF_INET,host_config.gateway.c_str(),(void *)&respData[index]);
>     index+=4; 
> ```

I notice that this patch assumes IPv4, and doesn't support IPv6 - you should at least point this out in a comment, if not support it.

---

*[chassishandler.C, line 397 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KLJThcl9Ym0Uku1D7R8:-KLJThcm2zEE4ReZUZKI:1292803925) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b5133820b90fa73a595885a9ce5ed33bf08f5892/chassishandler.C#L397)):*
> ```
>     }
> 
>     host_network_config += "ipaddress="+string(ipAddress)+",prefix="+ \
> ```

I suspect you mean "subnet" instead of "prefix" - it's the subnet mask.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90)*

**Comment by ratagupt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 28 unresolved discussions.

---

*[chassishandler.C, line 276 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KJiELOIGFi2qw1JwJ7G:-KLaMkeGMLjQtRb-QENj:1733988364) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b921c5937810192515ab905ebae381192a1a788d/chassishandler.C#L276)):*
<details><summary><i>Previously, sammj (Sam Mendoza-Jonas) wrote…</i></summary>
> Hi Ratan, copying some of my comments from the mailing list;
> 
> This "0x80,0x21, 0x70 ,0x62", and indeed the rest of the format are Petitboot-specific. While it's probably fine to assume we're using Petitboot for the moment, at least a comment here would be good to make it obvious for readers that may *not* be running Petitboot on their machines.
</details>
I can add ,I didn't add it as i thought that parameter 61 is OEM specific which self implies

---

*[chassishandler.C, line 281 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KLJSiN1vvq_w3EoMP-G:-KLaG_Dvfi4AKO-Oif4l:1302680628) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b5133820b90fa73a595885a9ce5ed33bf08f5892/chassishandler.C#L281)):*
<details><summary><i>Previously, sammj (Sam Mendoza-Jonas) wrote…</i></summary>
> Why do we do this? Is there a reason we can't just convert this string into the *other* string and get rid of the hostconfig struct?
</details>
Here we are getting the data from where we stored and filling all the strings in the host_network_config.I am just parsing the string (conf_str)and taking whatever is needed from that string..I need all these parsed values in different containers.

---

*[chassishandler.C, line 397 \[r2\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90#-KLJThcl9Ym0Uku1D7R8:-KLaI6P88N3ZCTxe9K90:1351650651) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/b5133820b90fa73a595885a9ce5ed33bf08f5892/chassishandler.C#L397)):*
<details><summary><i>Previously, sammj (Sam Mendoza-Jonas) wrote…</i></summary>
> I suspect you mean "subnet" instead of "prefix" - it's the subnet mask.
</details>
We are storing the prefix not the subnet mask and we are getting the prefix value not the subnet mask 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/90)*

**Comment by williamspatrick** [comment]
Please resubmit in Gerrit after migration.

**Pull request closed without merging**
