### PR TITLE
Handle errors finding openbmc_path #75

### PR DESCRIPTION
**Pull request by williamli80**
1.Check return value properly.

Signed-off-by: Nan Li <bjlinan@cn.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/phosphor-host-ipmid/86)

### CODE REVIEW

**Comment by causten** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sensorhandler.C, line 231 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/86#-KHa-gGvoKMkIXh-D0fQ:-KHa-gGwfI3bGeydu9S9:-247878950) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/c1717aecab2d5c1dde69bb06196f81d527a68a28/sensorhandler.C#L231)):*
> ```
> 
> final:
> ```

blank line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/86)*

**Comment by williamli80** [comment]
Thanks Chris. Fixed.

**Comment by causten** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/86)*

**Comment by anoo1** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/86)*

**Comment by anoo1** [comment]
:lgtm:

<details><summary><i>Previously, williamli80 (William Li ( Nan Li, 李楠)) wrote…</i></summary>
> Thanks Chris. Fixed.</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/86#-:-KHuxOo2KOzJruOTiafv:1417088721)*

**Comment by anoo1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sensorhandler.C, line 231 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/86#-KHa-gGvoKMkIXh-D0fQ:-KHvOwznZJPa416moiwl:1994772914) ([raw file](https://github.com/openbmc/phosphor-host-ipmid/blob/c1717aecab2d5c1dde69bb06196f81d527a68a28/sensorhandler.C#L231)):*
<details><summary><i>Previously, causten (Chris Austen) wrote…</i></summary>
> blank line?</details>
Nan has fixed in latest PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/86)*

**Comment by causten** [comment]
looks good:lgtm:

<details><summary><i>Previously, anoo1 wrote…</i></summary>
> :lgtm:</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-host-ipmid/86#-:-KHvqX1d6RBvKXNQt50E:74165626)*

**Comment by williamli80** [comment]
Hi, updated. Please review.

**Pull request merged**
